### ISSUE TITLE
Shortcut for vscode in WSL breaking when I use scm-breeze

### ISSUE THREAD

**Issue by AbdealiJK** [scmbreeze/scm_breeze#313] opened 2022-03-23 15:34 UTC
I use windows + WSL - it looks like it worked before I use scm-breeze

```
# This works
$ code ~/
$ alias code
-bash: alias: code: not found

# When I use scm-breeze
$ [ -s "/home/abdealijk/.scm_breeze/scm_breeze.sh" ] && source "/home/abdealijk/.scm_breeze/scm_breeze.sh"

# Now it starts failing
$ code ~/oss/codemirror/
-bash: /mnt/c/Program: No such file or directory
$ alias code
alias code='exec_scmb_expand_args /mnt/c/Program Files/Microsoft VS Code/bin/code'
```

If I then run:
`alias code='exec_scmb_expand_args "/mnt/c/Program Files/Microsoft VS Code/bin/code"'`
it seems to work

**Comment by ghthor** [comment] 2022-03-23 21:49
duplicate of #299

**Comment by ghthor** [comment] 2022-03-23 22:04
Pull the latest master now that I've pulled #299 and this should fix this issue.

**Closed by ghthor** 2022-03-23 22:04 UTC
