### ISSUE TITLE
Why does gd now add "--"

### ISSUE THREAD

**Issue by pmeth** [scmbreeze/scm_breeze#139] opened 2014-04-23 16:51 UTC
May I ask the reasoning behind adding -- to gd in 878d81a4bde5dc7f5ee59f833d7f4b354388f797

I find it quite useless as I can no longer compare my current branch to another branch using this shortcut, but I would love to hear your reasoning.

**Comment by ghthor** [comment] 2016-09-02 21:15
Hmmm, Any thoughts on how to fix this with a simple change? I'm looking into it as well.

**Comment by pmeth** [comment] 2016-09-02 21:24
i made my own fork and fixed it there like this https://github.com/pmeth/scm_breeze/commit/552f7eb9af2937f2d4393b7ab6d6c88f14ff5358

You could do the same.  The only issue with this is you may have to manually keep your branch up to date with the upstream.  On the other hand, this may be good so you don't get new "features" that you didn't want when you update.

**Comment by ghthor** [comment] 2016-09-02 21:28
Hmm, well yeah. It seems that ndbroadbent added the -- to fix behavior in a directory that doesn't exist, probably due to a `git rm` command removing it. I'd like to not lose that bugfix as a regression just to fix this.

Also, I am now the maintainer of SCM_breeze and while it isn't my full time job, and am 100% committed to fixing and pulling in changes that the community has developed in the last 2 years during the low level of maintenance provided by ndbroadbent.

**Comment by pmeth** [comment] 2016-09-02 21:35
nice to know someone has taken over.  It is a good project, though a few small behaviours I don't agree with. Like this one, and another one that ruins my `ll` linux command.

I don't see how adding -- will fix directories that don't exist.  All it does is make the gd command only work on files/dirs and not branches.

**Comment by ghthor** [comment] 2016-09-02 21:42
Notice, that the referenced commit doesn't have any tests added so maybe we can just roll it back and see what happens.

**Comment by pmeth** [comment] 2016-09-02 21:55
it's a lot of code and a pretty old commit to just revert.  i would say if you agree with me, then make a new commit similar to the one i made on my fork (and maybe also remove the -- for git_diff_cached_alias. if you like i can make a pull request.

**Comment by pmeth** [comment] 2016-09-02 22:02
i have not looked at the recent updates and I think this issue may already be fixed.
https://github.com/scmbreeze/scm_breeze/search?utf8=%E2%9C%93&q=git_diff_alias&type=Code

**Comment by ghthor** [comment] 2016-09-02 22:03
Ooooo! Maybe we've just saved ourselves a little bit of work! Good catch!

**Closed** 2016-09-02 22:04 UTC
